###################################################################
#                                                                 #
#              CreativeBasic                                      #
#              Version: 1.0                                       #
#              authors: NewZ_AZ, Larsouille, Quatre               #
#                                                                 #
###################################################################
test: