name: CreativeBasic
version: 1.0
authors:
  - NewZ_AZ
  - Larsouille
  - Quatre
main: com.crealabs.creativebasic.main.Main
commands:
  help:
    description: "This command use for help user !"
  back:
    description: "This command use for teleport player on lastlocation !"
  warp:
    description: "This command use for teleport on warp !"
  setwarp:
    description: "This command use for create warp !"
  delwarp:
    description: "This command use for remove warp !"
  gamemode:
    aliases: [gm]